remote_theme: just-the-docs/just-the-docs
title: Everscale for solidity developers
description: This tutorial is about how to understand 'Everscale' blockchain if you familiar with basic concepts how ethereum works and have basic knowlage about solidity language.
search_enabled: false
aux_links:
  "This tutorial on GitHub":
    - "//github.com/mnill/everscale-for-solidity-dev"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/mnill/everscale-for-solidity-dev"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"
