remote_theme: just-the-docs/just-the-docs
title: Everscale for solidity developers
description: This tutorial is about how to understand 'Everscale' blockchain if you familiar with basic concepts how ethereum works and have basic knowlage about solidity language.
search_enabled: false
