theme: jekyll-theme-cayman
title: Everscale for solidity devepoers
description: This tutorial is about how to understand 'Everscale' blockchain if you familiar with basic concepts how ethereum works and have basic knowlage about solidity language.
